apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:YXjVM1D6vY/OXFwaqFCQr9ipw+UqCbqLPPNlWdfZGns=,iv:n0gjKUQ8r7Cmu9qylEOW9kktpagZy+MzZCi1fyS7ack=,tag:rNHKngB5Z8pRqTPmbjccpA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:4UG9t/+4m2XAZ5Ojm31HxfSrAopV7Dvy58n9aJzygSLyBmIPWYlIwUdQTQc=,iv:ET1po6HCPWDGBJaj8xHld+2nhwK8rSAgfBJ7EVkO8jg=,tag:lHfvJHkzjQZuwHjws0Og6w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZG84ODE0TTRZQ0ZiRkFR
            bG14TDBJQjlUWE8vbkl6YkZnQklNdW1XUVZVClRzTUJjSFNtNkhDZzRyN1ZXcE5C
            M3lrVmtkV0lQM0c3ZWkweTQ2SDZlZXMKLS0tIGFEWEZtczJ2dnNmSHZGS1ErVzBz
            T25ad0ZZbjJVNW9uMEJQd3lJcWJCaWMKvm48tZbZ4jtFqpVHFSxGz3QnWXhs5Acn
            0iOpzc1ctWMW/+P2f0fWy9iiYubNgHPRkXg0mA7Y9BMvElS3CAOQKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVlZUOTFxZGpkMnhSTmR0
            aktSUUlMSm9Ob3ZrOUVCeHRZWmJxcEo3NndZClpCUENiZTlYUUFrc0Z5UHdaSHhZ
            dFJVQzZaSWZTYjlMRWtUZWhGNzNGQTgKLS0tIG9Md3Nwc2RONjJhOXNXVldLMlFM
            ekM5WU42YWk4MUJ1c0tEUHN2T1lINkkKIO37pGpxpycM/u99GovhVNIEzSENvB+N
            YD15pqxEqfzDPxflmW+P+yEbxGpGpYO9zlCJyHAOJerobRfMiGvh8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaldPUEtrci9sQXMrWmEv
            OFFsc1laY01ZSDYyNHV0VjNLOXdCYmdLKzFzCkg2b0UvSTdSZEhTV1RETW9MMCtm
            ZXBNaUJPNWl5OUhpajBTVUtKbTVON3MKLS0tIGNaS2RTSkVPM2I5dS9YUmtLRlYz
            bUVWT1JFTUVVMHVCdi9qcWdYNzhDdG8KtRz61bQJ9JqBYW0tbQuvPJaQGryRMrH2
            dU6OdBWy2In8yxd9vTgk+jEtvs2mEGe01KbAp7R6AhQTqvymiR3vPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VDVjdDBuK2pqSy80VEhw
            dEd6NnNtNStEQlRqc2hBK0g4M3poVTMyZm44CmZwbjlQUUphVytKQzRPb1FlcXBv
            L0ZIYWlQbWs0ZEtyWFRwMlNPQ0dNNHcKLS0tIDdGd1FJWFBkbTZqUkc3dlluRDl5
            Q1VUYzRvckovZHNDRVhyekIzeVlnQWsKFN+DbdSThUHWgWMbFEpbvl1wI8h/T9Pb
            jJ+YYFDV2HwsCOjBrkiUxujiK59dkBQ1X5nIDKDzwT2v7X7EDoRbIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:10:05Z"
    mac: ENC[AES256_GCM,data:JOJUgsxijEiRFb4LZZQRoJdM9ppKxkPnQUrWFeLURFoddhgjOdos1BYDEzYGarL5tOPrZph1P2An39KYUlt2hcnYsv5j0tEOj3NxeuVhAWUXs3yMei6i8XUbxc3FjsWSVfCAFuvqicywthexd3AzH7jdHXt7xGZzJj56cOponlY=,iv:iXJEGdloBK4AIWwdeIj8EZzV7vMcT/Gzy/QNy6+vBQk=,tag:DUl9i2BBQXtj8Eh0aoyptQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: authentik-db-credentials
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:X/Dy+NIPfE8o0ztYUoOOYHG/U5mdh5AFiuHOaSU1vPw=,iv:t+V+xb3OSwb+pSut5c5l8ZpWN5L/HYt8teAKh/YmT0w=,tag:lnXlt+ztccOlsQxrcPoNKg==,type:str]
    username: ENC[AES256_GCM,data:ntdMPjsSGe63,iv:E8gB4MB7BjZTg84nFQz5KP4CHbiSFf1YeYJdQ+KFo6w=,tag:0aKjU14GJSRYJKRzkHpcrQ==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZG84ODE0TTRZQ0ZiRkFR
            bG14TDBJQjlUWE8vbkl6YkZnQklNdW1XUVZVClRzTUJjSFNtNkhDZzRyN1ZXcE5C
            M3lrVmtkV0lQM0c3ZWkweTQ2SDZlZXMKLS0tIGFEWEZtczJ2dnNmSHZGS1ErVzBz
            T25ad0ZZbjJVNW9uMEJQd3lJcWJCaWMKvm48tZbZ4jtFqpVHFSxGz3QnWXhs5Acn
            0iOpzc1ctWMW/+P2f0fWy9iiYubNgHPRkXg0mA7Y9BMvElS3CAOQKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVlZUOTFxZGpkMnhSTmR0
            aktSUUlMSm9Ob3ZrOUVCeHRZWmJxcEo3NndZClpCUENiZTlYUUFrc0Z5UHdaSHhZ
            dFJVQzZaSWZTYjlMRWtUZWhGNzNGQTgKLS0tIG9Md3Nwc2RONjJhOXNXVldLMlFM
            ekM5WU42YWk4MUJ1c0tEUHN2T1lINkkKIO37pGpxpycM/u99GovhVNIEzSENvB+N
            YD15pqxEqfzDPxflmW+P+yEbxGpGpYO9zlCJyHAOJerobRfMiGvh8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaldPUEtrci9sQXMrWmEv
            OFFsc1laY01ZSDYyNHV0VjNLOXdCYmdLKzFzCkg2b0UvSTdSZEhTV1RETW9MMCtm
            ZXBNaUJPNWl5OUhpajBTVUtKbTVON3MKLS0tIGNaS2RTSkVPM2I5dS9YUmtLRlYz
            bUVWT1JFTUVVMHVCdi9qcWdYNzhDdG8KtRz61bQJ9JqBYW0tbQuvPJaQGryRMrH2
            dU6OdBWy2In8yxd9vTgk+jEtvs2mEGe01KbAp7R6AhQTqvymiR3vPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VDVjdDBuK2pqSy80VEhw
            dEd6NnNtNStEQlRqc2hBK0g4M3poVTMyZm44CmZwbjlQUUphVytKQzRPb1FlcXBv
            L0ZIYWlQbWs0ZEtyWFRwMlNPQ0dNNHcKLS0tIDdGd1FJWFBkbTZqUkc3dlluRDl5
            Q1VUYzRvckovZHNDRVhyekIzeVlnQWsKFN+DbdSThUHWgWMbFEpbvl1wI8h/T9Pb
            jJ+YYFDV2HwsCOjBrkiUxujiK59dkBQ1X5nIDKDzwT2v7X7EDoRbIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:10:05Z"
    mac: ENC[AES256_GCM,data:JOJUgsxijEiRFb4LZZQRoJdM9ppKxkPnQUrWFeLURFoddhgjOdos1BYDEzYGarL5tOPrZph1P2An39KYUlt2hcnYsv5j0tEOj3NxeuVhAWUXs3yMei6i8XUbxc3FjsWSVfCAFuvqicywthexd3AzH7jdHXt7xGZzJj56cOponlY=,iv:iXJEGdloBK4AIWwdeIj8EZzV7vMcT/Gzy/QNy6+vBQk=,tag:DUl9i2BBQXtj8Eh0aoyptQ==,type:str]
    version: 3.13.3
