apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:W1RukifGSBBFPP4Amn8hT0eDNIfQqTWUGXU9PcxXKtPfP6Ju3ggnIru6yYQ=,iv:BORwXZlWNwxRyHlK1uUD8skvIy9OR/IwzPU/DnyV7l0=,tag:PkSLvgGUywes4Htj7M8+xQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Ge8G74gU6HTPefyTPgpS/T76OkG29Q1Wg48IShmBLhE=,iv:F0lfEjmfy2PyvFNYtu/o86e3arNFc27J7XmoAejwJ1A=,tag:E8brN3E2+qJPVd0Zp2cXbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbHZqWk1Pb3o1ZjJQVEtV
            NC8rTHB5WkVTelAxczhwb3V3OXlITmJaYm5RCmt5R1FnSTNtRTdHeUJQSzF0YTZk
            bE9vM0pPNDRXZ0lrYlZsTm82MnBwb1EKLS0tIFdjTFZuOElPT0k2WGdBd3FacG4w
            ci9MbXRvNG5FSEhaTjB3eGZNUjRkZEkK4XXjnKl3RGzBHdSKoAPU+Lxbz/x9oeEg
            v6bAnfoAxP82btYNLe7HgNaLftkrZmWxuZPerC7QxWbhpZUnHvmUMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeXpvSjZ5VmhVelZHSm1s
            aDhsZWlsL3hEajNSMk4xcDFCaGJLUVNwZlJBCm9qSjI2eGNVSXNNcldiK1h3MkNa
            eVlPb1VZK2xDVFdyRmlSWDlEa3BiN1UKLS0tIHRNYzI2eDJtQzhvOGM3Q2o3L081
            WDF4eUd3WWpXNC9JSFZwSUlmWXZGMW8KaxhkT2dadIeaFjgv5zE13+u/4m5D+jz6
            UHevsxzICaq06cLDZB8G6c7rHO5Fj5fobHSTheeIpBiElHH3ZfIY5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dlBhZUdhMk1SOVltRmFl
            d3FFd1FzaXJBVC9OZkJsYUFZUFB6MnZ1aGxFCkVRK1VCTUFRQmhtSXl6UW1EUDE3
            bFJrczBtZy9CYzd3T1dmM1lmellSTWsKLS0tIHRPSUswVnJBMW1LWFg3MHdsd1BF
            aTNPQTBaaU5Fd3ZJbDY5MVRJYXZrWUEKbCJLPefdF2BSfEGXtcxIDlYNzLp+Px52
            XbDc0DPiZhkDFPqL3qNOG16TiePpnYTUfJ+Gt6RE3yUsEtvg+5CElQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU1BJQWFNdFY2b1RSaHpi
            WitoelYrQ0VOb2N3Vm1WSnB6U3hSMGNuSTFvCitzaW5NK3pEYzdQbWNjS2lwNXhJ
            MVJGeWJTc1pzRXg1NU1ZdDZQNk54OXMKLS0tIEFPeXMwQXJ1WmlzYmJ0UjVGbnFw
            Rk81NXZRTEF5ZzFMekRDVlkzL2ppajQKZUKfcGCIU1gt6rzmtMmriKO+PXn83a0p
            RflMN6raQUBJUpOTyv1/fi8X2CWHyWTqE1nhiBHlOrSbzzvclrM7ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T10:59:24Z"
    mac: ENC[AES256_GCM,data:rfFT2mdyxdaE8KjSCK5rvrflMCv97z9xXgyJEaOra/sq/hQWFnYfop4NYZDyfR2L7Twvo/sgqauLwmtJmxskUWj5xxgIprKSSU386HRX3aYaU+ILVOG+HruPEskhT6YiJUUwqqnwJwmm7l9u8flyTaVlxGjklQTd+FzhRs/9Rc8=,iv:jPMQxpYwuyt2PZ+3zzrhb9T/hflfli0VNN6TfoVjsDY=,tag:TQy1gFfMX2teeE7YuOaHJw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:y3eZn8zOh+c4,iv:0iJbVBjcGxbCSG4LszovHAMlNcMlXXSCQTRfWiyGZIM=,tag:rSFBGzokA2+h2ckDSsLjiQ==,type:str]
    password: ENC[AES256_GCM,data:t8FY8+uWHUgo0JhGpQYQnBBNnwjGVEf2YR/bs0PUDgQ=,iv:fwssHUUN2ZClJ8+PrHw07c3l0dX31xJdjyKJjsrcpVM=,tag:SeTe9zdQaPDwN0a5wdNDPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbHZqWk1Pb3o1ZjJQVEtV
            NC8rTHB5WkVTelAxczhwb3V3OXlITmJaYm5RCmt5R1FnSTNtRTdHeUJQSzF0YTZk
            bE9vM0pPNDRXZ0lrYlZsTm82MnBwb1EKLS0tIFdjTFZuOElPT0k2WGdBd3FacG4w
            ci9MbXRvNG5FSEhaTjB3eGZNUjRkZEkK4XXjnKl3RGzBHdSKoAPU+Lxbz/x9oeEg
            v6bAnfoAxP82btYNLe7HgNaLftkrZmWxuZPerC7QxWbhpZUnHvmUMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeXpvSjZ5VmhVelZHSm1s
            aDhsZWlsL3hEajNSMk4xcDFCaGJLUVNwZlJBCm9qSjI2eGNVSXNNcldiK1h3MkNa
            eVlPb1VZK2xDVFdyRmlSWDlEa3BiN1UKLS0tIHRNYzI2eDJtQzhvOGM3Q2o3L081
            WDF4eUd3WWpXNC9JSFZwSUlmWXZGMW8KaxhkT2dadIeaFjgv5zE13+u/4m5D+jz6
            UHevsxzICaq06cLDZB8G6c7rHO5Fj5fobHSTheeIpBiElHH3ZfIY5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dlBhZUdhMk1SOVltRmFl
            d3FFd1FzaXJBVC9OZkJsYUFZUFB6MnZ1aGxFCkVRK1VCTUFRQmhtSXl6UW1EUDE3
            bFJrczBtZy9CYzd3T1dmM1lmellSTWsKLS0tIHRPSUswVnJBMW1LWFg3MHdsd1BF
            aTNPQTBaaU5Fd3ZJbDY5MVRJYXZrWUEKbCJLPefdF2BSfEGXtcxIDlYNzLp+Px52
            XbDc0DPiZhkDFPqL3qNOG16TiePpnYTUfJ+Gt6RE3yUsEtvg+5CElQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU1BJQWFNdFY2b1RSaHpi
            WitoelYrQ0VOb2N3Vm1WSnB6U3hSMGNuSTFvCitzaW5NK3pEYzdQbWNjS2lwNXhJ
            MVJGeWJTc1pzRXg1NU1ZdDZQNk54OXMKLS0tIEFPeXMwQXJ1WmlzYmJ0UjVGbnFw
            Rk81NXZRTEF5ZzFMekRDVlkzL2ppajQKZUKfcGCIU1gt6rzmtMmriKO+PXn83a0p
            RflMN6raQUBJUpOTyv1/fi8X2CWHyWTqE1nhiBHlOrSbzzvclrM7ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T10:59:24Z"
    mac: ENC[AES256_GCM,data:rfFT2mdyxdaE8KjSCK5rvrflMCv97z9xXgyJEaOra/sq/hQWFnYfop4NYZDyfR2L7Twvo/sgqauLwmtJmxskUWj5xxgIprKSSU386HRX3aYaU+ILVOG+HruPEskhT6YiJUUwqqnwJwmm7l9u8flyTaVlxGjklQTd+FzhRs/9Rc8=,iv:jPMQxpYwuyt2PZ+3zzrhb9T/hflfli0VNN6TfoVjsDY=,tag:TQy1gFfMX2teeE7YuOaHJw==,type:str]
    version: 3.13.3
