apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
    namespace: coder
type: Opaque
stringData:
    db-url: ENC[AES256_GCM,data:g5ENnTcVjGVg9DXk0+No2b+5DBdsAYN3mchpenFrYS++ZN+1SjQWNnD44ZJZjwZnHcIJpTF/Go4FkYe4bkfFhlfl9eqwk5NZB5ZjjlOQ4q/I3HszPc0xWYUy0GQCifDpjsasqjLzNHwzWaJ7kDDbgAmzZ5A=,iv:up6YUQMBkOpIazic6tkCjnbALQ4/PukXaqBw0YS6PCk=,tag:dB2iqbeXpOv7Rc2JbrP0FA==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:QtiIuD5YvDfyGXNvoFaggYUSAO0UBI01jdMZCpr+vHzaN9AY,iv:xPz0MeVBi/65sunN53bpc+8VAunt0YRTRBuaS+fr9wY=,tag:/W7ws8hfLqGvq3iqnxuSlQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:t9/hg7V4Vp4XT/Ks57ebCILunOilk1jzchBYpFjprJfogdUwW7mCnIlkT9w0WrKe9pWDIK/Y3SZM6BNWcFv2Yw==,iv:lnxcSCJCkuPWBZ8qOXToLlHO1IcqtFMCckpnk3H6FZw=,tag:gfB9E+Gszo4K53WmqfmNBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y2Z0WmZOUlI1TEJtbERp
            TzdlYmVweUJUZzY2MlBQMW94TGpXdHlWeldBClJzQkt2c0RFbGtwdXlIWSsyQk0w
            SUtWR1dNQnhzRnpXMlNqclEyYVc0T1UKLS0tIE1ST3dETGZBU2g1dWlhNlBoNStE
            TVlCM0RvMFZWczhKUHFmeVROZ3lyWDgKEC+LySmYRBeHj6fDm0qBXCsC23bkpJG1
            vLJ2HcnnRVOb901UWhERWi9YTUig5fGBufIAd44s0RUXAYgLa1VePg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXNxSTQ4MFRiZGtSYnlF
            L3pabWxsa2twNS9SN1hVRjNKbVlTZHE2TjFjCkhFNjNIZ0FvZFNyWS9ZNVdkREdY
            ZWpDVjdaclN4K0t4bnMyQ3hrOVR4T0EKLS0tIDZCR2JQVS8wVmpZbmhiWk9WSFdR
            NEY2d21qNXdkTWdVWmRtc2o1QzdjSkEKIneafPJbe3VacM27kyjkO3ElqSrdjRZy
            0bvcBAmSI8vJw7cJ6VixAZJTNM+XDQjwK9X9FCHTcCyeMkaEtLEvMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcTU3R01JclppTmhmMHZ5
            bHpLSlR2eSt1RVNwaWptK1A2a3kydTBRMTNrCjZabGphMjlYcEFOM2dPbjN2Z0hJ
            azlrblp1UDI0NktRVStPQVJJanpwQ2cKLS0tIEQ3SFU4VmI0aE5zVEgrUGV3SEc0
            Y2pSR2sxNXFnVnVpa1VpYS9jcGg3OVUKp6D7xirOym6dJxqnrV0G4yb+zwPvqnr8
            y3L8W/zert/fBANCOgdIOnBIlinwfjRZS1HLBiCCSJsPBXPdnJrLUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYczU5WVQ4TTRGR0ZIbVJX
            UldVS2FGZzNXcG5lcngxWHQ3OVo0TmZpQ0dRCnN3WUhEaDFhL0hUbmRFK1BHQW5r
            Ym16b0F6QTA1TnlZNHZpV1kxMjhFNVEKLS0tIHRQM290ZmVTTFEwYm52cW8xMGtr
            cFhvYjdZbnd0SnFsZGNZMy9laGxQcFUKnVFDMcS8wKGZiuasS5jah4j+tkmgGswe
            ngf0wtga8bAOP9UHD6q6rE3qLd0bdlE7Omp5EvwjmxGav2CEfTtzuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T07:48:49Z"
    mac: ENC[AES256_GCM,data:/6yFGREpCKXdUqqb/QJeMNwZL2NepXIlsIdHxVBIXldvONbAUJ+BcFzHhpcAxZPmWjlk9OMbCjU47XedS56NGVmz1dpq8ae7VG0/bjhE/cCqUTa1IXYs2F6lZidpPQMnBb3xRKD33uGmqZPIMLcotHwPEthYPyQrh6a/gHl4gfY=,iv:h/NLHVetca24Gb6zJtTU55DfSKl4uB4Lz6p+xHXmRUQ=,tag:vCoxrHY+lb/oYGk0jF7F1Q==,type:str]
    version: 3.13.3
