apiVersion: v1
kind: Secret
metadata:
    name: coder-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ynSt25Y=,iv:WqurlIhb+B7KQKjtM5mZRepj95Zv4T6xazcqCUyh8Q0=,tag:OKWwXJ7ILdK/hROftsQlcQ==,type:str]
    password: ENC[AES256_GCM,data:iQ2X1mXDfJYe9BdzoowW2edaRlhbN21W1zDKcEgC2xQ=,iv:pzs5hhdbIbMADRGvE1CvoTVyPxso74vB7xX7vnQtL1I=,tag:wagH5bXCMF+9qPAzDhwTHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSjFkM3BudkhUQzVjQlFi
            RTJudnhhZXM2Tm9Ic1phc2lkRWdhanc5am5jCmFYamxkNHZBcjNhNEJMN1pkWlhJ
            NlVwei9jUEE4ODNhQndGZUlGZWVBbTAKLS0tIEI0WGU0Z2tyZmU4T1ExVmNuaWQ0
            NU9tWDVGbWg4bi9sb2JVUXVTTjhXaUUKhJlPYRLMyhidOWZ8RucPJ8LRYXd7El6d
            UKwg1mjpQmECsM7bXfRTXGn7S6bPyS6+OWFhRMGlTAPz4BMWmFmYhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UkVBd2FmdlRRdFRPOExj
            TjVDNTNUajBGdk54U2E1bU8xMFdwKzFZTzI0CnZqQzNqVk1xNys1ZlBGRVRkdkUv
            NWIrM2o1WTFWTzlwSmxHZUJPcGR6YzQKLS0tIHVjODBqQkJLL1dCNjZzMHVIMnVL
            VDVHcUJIYVA1NWZUWTZ6MW1pRHhwV28K2MrGLC55Kcry9kMw567TKJn/iuN7GB55
            ZQb2zYp4o6OBYciTnwqViEwos+8zyOBBcgdAHVHwnntDed5PgCA0sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eW55Z2JrOWUwMnRLaHdm
            bGRQbmZVekNmSmhSeUJHL1EvcXZGVkRFbUNjCnFGWHc2MjlJdGtESW5tSXErbjlU
            U2ZjSWg4R250b05ORmtVdEh3OXJqMkUKLS0tIEhWb24xL0IwakR0MnBlYWNsVzht
            OWZEcVZCNjBRdW9VOFh2UzB2Z2FJeVUKg/z1l0/7GNpxWF/7P7DItgAffHJlMsn5
            TW3XeWFuLt22mVsO7zqkKmlWMSQmhbG66dwptcFRkSKVKWEirNgwLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eWNiYWhwK2szWDNrbm8x
            bHl2OVRhSGtTWStyWU5OVFdmNWl5VGNURWxzCmFVREdyOVF2YXZiYk0vZ2tQSXh1
            WTVWdTZxMXJzNGhOc25CckFxS1ZGMlEKLS0tIEh5c2p1SWg2Wm1qMHRPUmQ3dDN4
            QVQvRWcrWG1BSktVUmFKWUEwcmRIMjQK/Ug+gjL7wZWt8z5X4mAkCggrcDYeUcac
            XAjw/QZFkvY+KYnp9gdC/qbrsbBR/DLaRXGCy+dsK0KSpbaZ8H5bnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T17:01:29Z"
    mac: ENC[AES256_GCM,data:ed0AMaerSAv31aKt93vWmnq1wr4C/9ZZScOKECaYB94pDb9ZDtw4iQZuG/XFkfBs9JZ72FCxkCYdj328K9Tb02KbVK5kpSDvuMy4O9JJbBb3XcG/6QK1G+SoilUev0UhD3hVsxXJFQwL8BR4dZd2fmyvBkWlPehgE0iaJoqGBjc=,iv:HUtVAmaFNB1su7wjtm2trn3beLTm6dxiNPoAcYo1260=,tag:8/LMOqR5LcFIVRV5u1n4EA==,type:str]
    version: 3.13.3
