apiVersion: v1
kind: Secret
metadata:
    name: coder-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:FUmG420=,iv:smr6qO996UbSTx1R0POqR4ZadTiUP/N8EmGzufoj96Y=,tag:PtPNsWJUOAZxl65ugE7MvQ==,type:str]
    password: ENC[AES256_GCM,data:ahX2B+C0B+a0U3INEHBDhfSTuma5Ta0OOwZ3FNbFTkU=,iv:SMNH4UXYOsI07yxkKOb2aS8jABBM+wdLPi4WbPNbhQc=,tag:RHsLV5g/HfzMuAjhtmxEIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRK05HSHlJYTgvUE93eHdv
            QXR2ZW5vZUx5KzV4OWtCdDRXSEtNQ0dZU1JVCjh4Rk9NU042cStxNHRMVUR3NkFi
            KzJmSHlMOEExUnQ0S0lubms1ZWNhbUkKLS0tIHE0dGNCeTM3dUQ5cjlpOFR3aDZr
            RVpPcE14NEN0RWJ3bFQ1dHdtV2RCdEUKXPzg2LoWqVGlw2hdMrvD5dPlPAPgKhr+
            vIpV4FM+o79RgRXJGI9xNiYNnpj5Fq31YY8Os/5yVCsWQ00hrQqDzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWmdpejZ4QTVQd0gxRERP
            V1VjRkZIOFBLVklNRjdEWkVlVGFOamhFWVZnCmVLVHhxQVFUSU40K21aOXFJVXBp
            ai9XTWdUMForYVlEMVFZUmtoV3gyM2sKLS0tIDZMWkV5SmVQellQRmhEcUYyc21F
            U0JTZHVIM0lTbUVjcjN0b2IzamNZVEEKtdfU8ITEBNhy1vI9kBbsZdLxvLxhs/Tq
            264BWF/CBDHPgt4gQccBRDWz5KvRnJv1lvF0ZkVZhkBLNCQwdvYDew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dWM1bjgxS3NETW1GMDMr
            eFdQQnNTV2NheXNKU3JjWDhLWTVSZ2dIYVFzCjY5Rzl1T0lNcGdldEV4VStNcjRZ
            T1dvZXl5YU9scUdPQjhPeTFnTlEvUW8KLS0tIEI3Wjc4dC9sZ0EzOGtvWUhjU3Vl
            WnBkNkgyMzd5NmtqNG5VcWtCRis4U2sKue1GODQuUmd0jjxaYHil1of79gfaitc3
            ftqM5aSmWy8RnzUWdcIGiIItk2nDM2Xg3L+QbIF8bydSSHnQX4VLQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcEhzUDBKa0lWZlZoTVhB
            dm5rbndIbWkxYXh3QUEyTFl6em01bkJVYW40CmpVaE5rdU5teEtRWlZyTjNBOEcw
            L21sZVFKclk3aEFoVWF0ZHZLSndrT3cKLS0tIExmek90NEFUOFp1OUFDZWVRYS9t
            T21aRWI4WkZXYjIxSWxXU1djY3V4VWMKEuv0hU++aH56wldr6spd8q5bAjmE2wSb
            hGERDvTNhngy7PP7/cVqfczrOqjZQebpJcRYLC1dKiLoAPPYBwYyyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:16:30Z"
    mac: ENC[AES256_GCM,data:hgSVyeqS5HJEJRvUMN+2KUGzRaZzCWaE63E/SYVwn4mr3Kte8EFRORFjDE4b+SsgoG/1rET/nsX0ChaoHPTkgNytyUgZVGhJVwzRAmCI+izEM1XkQHIN8txqf3Wq3lq5qvH5pgNGlgrcydk2rn6szuCuZIq9xRKBKsSGsOiCLuY=,iv:APgLedw5yGKKno6SKqr8t3JboF88Wf6voWxS3FL9qLg=,tag:nQkAmDdwSL145oOPfYsCwg==,type:str]
    version: 3.13.3
