apiVersion: v1
kind: Secret
metadata:
    name: coder-db-credentials
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RL0wHaA=,iv:n1nrQePvXRdasl/ivSTl+11FxGJ8cXNvZ83yB0QQbr8=,tag:Z5KguLeNcT0gfF1JJz42rA==,type:str]
    password: ENC[AES256_GCM,data:ng0HctaOgeaCPnbzkVHur1rub/2yQkkeoYhHU0hcQrk=,iv:SkPSwxoplX3VLz/Vu9Gm/5fVWTxzkZiYcxWBbx8FzD8=,tag:2vU+qKuW/dJQ471IO6TVrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYk1sbVJvUVViZjI3Q3FK
            VDRVcHRCdWZoR0xoNU5OT0JPYjRIWXFrdFRjCmZpWk02M1JVYWdiSkkvSzZpazEx
            NldwWDhmWTdPVTNlbjZ3em1VTTJUa0kKLS0tIGgydXdobFJUWG5Cb3hIb1gyaUls
            d00vdjA4WnUrUnU1b2tBa0syN3BlMmcKb+8nto2QFoAEDO3TJ7fVcf945ycrP0Ae
            js5dTxMG5t5vlptmICYRnEMSXBYplTpvMF7owOjmVtwAdXbRy317tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOW9jTXYxSGN4YVB0Witi
            MTdWQkFZTEdITWZyS1hvTFVUZzlvbWNtSUU4CnNvSytUMjA4OUY5MU9sZ2ZKL0RS
            ZTY1UHlJU2tScjZqUFd1OHJvbTJCSkUKLS0tIElxWXo1OFZpSk80ODZFelNMM3lS
            THJhbXEzUVBJNEN1VU9lSE9tcXY0bTAK4bxP2gfFX9DlLyuvWbUM+k4WuXC43siL
            CJC4LR1KKf9qJN8H7XCoAMK2UGSYnwqpMoq7GSa20JYCIjl6bE09SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeTY2MWc0ZzJDSkJCQ0Ex
            UXFRU3kzVW4yb3JzTUcwM1VoTWFjbmtoWEg0Cll4RlJsTThHVXAzTDl6YmZ4KzVU
            ZC9BdzRyQmxNOTg5dCthcGNYUnVENGMKLS0tIFpGTWZldUhuM2JTN0Vndkg0eHM5
            amI3T2txVHh4M2pSa1A0SW9uVG4vRDQK8d1akMvQetxNrk4dwLAkM0h757iNEw/+
            DV0S7mfrvq0vrgKCAYxXLk3tdi+TKkJAASVERj1NBXESNMrl+Q/0wA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTmNGRm16c2NuR0hjako3
            NTRHdWhBSHNvVlk3YlVvREtrbW5nV0VwNmpNClpOREg1K2Y3UDBBZU1RVTV0a1V3
            NnJjZkNSUTJyN3lYWFFiWXJxV2poeU0KLS0tIDFNb0dSc0l2TjNiM0VnbDdzTkZn
            dVpWWGh3ZkFaSGd3L1NBQm1yM2Q4dk0Klhdm0odkcTi/2dki8aknatfOt/P586i7
            J3uSep9h+gw8xss+nd0nAITNjF0CbQPcUYhc4Et5NdziepbCG5WNJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T07:48:49Z"
    mac: ENC[AES256_GCM,data:SqPFyLVcf2tRC0p92U8MatszFzPS57OkChT1jbW+lPU3Uw4/fr4SGlmuoCd/EUj+rIKE+AdW4SXunSRSOSkRiJQQGogtCk8l/jzf3771jCUugaDWP3u1lSLs7aaXsQndF4NsUdOWatDAN76MQlenfruHnx8TyaeSd4PBcM/fL7I=,iv:afPVCt58UMaGAIPwhXSO9URNzo13e9RVOJ0H+eAXxgs=,tag:WMh7An6yqpqC2pFasY9GZA==,type:str]
    version: 3.13.3
