apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
    namespace: coder
type: Opaque
stringData:
    db-url: ENC[AES256_GCM,data:DjRv3aglVp+V9WIbcBt2DIBJmWfBmuBTfGKSNcq1eWj1Eh2rBAT+Tn5AXPhTrcvdjMWMuthZuxvpTU2Fm8ze+rfHnfAOjRDv1L2XuiMCWsDhlYPqYmtURS5G3JR2/GTzBWYimP5/D1KWiIqpSYDI4lBJ7Uk=,iv:bbq0RgdAgdQHE3tYfZ+l2kUjqyolIP9zRH5olBSIifs=,tag:30A5nWSrQrmtifpUKfzrNA==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:Rnu0rqCbvbtBoajP+IX1gEAkFgNH2EGZswphwwdlrJ78xWOw,iv:X0jMvmrvqus7U6LQ0/2HzdF8iPegOlsOtJZJsQzPOYM=,tag:yRrQZlV1u7J7OeL+Q9AAFw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:sMo9oBL4eHdM77Um5eLb4zteYTcMdKee5wf0V+qSs16tHUv07PASIqm6nUaFhWhxVO/Hl3enTmHD6WxF84kRSw==,iv:nxjhtxWc6h/QA5YzDA+eBOdSpz9CXiJNWQ65SLfDGx4=,tag:BixQJ1EGmgtOVNabHZ0mhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZXMxZDRkQWJ2SFowUWZS
            SGdGbk96Y3VSbGZYUVFUZ3ErTU10WUFRU0N3CjYzNTVLRkd3ZllZd0lTMTlDTGVZ
            d2RSbmk3UXY1MnNDM1EwNnRHQnJtNmcKLS0tIHZxU1V3OG5DYmNjck9xY1FZYW9s
            dzVBcWh2OWdjMWV6Q2poOGxWai9XbzQKe20B7Olo12/nTAOlvc0CPUURMktPZkAP
            Ov9C8K6XBYt3daqtcSCPccBR7qOu/O34mbLBurjtTJy3qFaUTHxfDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSk5vRHQrTXpKVVZ1ZGRF
            b0FPWHNWRlVaRVdDMm5kQXVPSXhnQXA2VENnCjE0OEJFZE5kTGRQbjlCVnRoVjVP
            ajRsSlpwVGhFdmVuUktrcDIwTVFqWEUKLS0tIEkwU3hTWHB4b1VtSUgyRWxabFBK
            SGVWN3YxdTZST1c4d0xiVWFTZlNBZHcKol4dEmYqESKpL1jgG+dJIdI7aUxxe28V
            RReVmczcx+koLHxSqKhPJzgvqktDcKd3GV/lhw+s5lTJ3IVfs37fHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTTdITEczSWJVaWJPZnB0
            ZEtPRnVlTktaUE1xSG9pUHlOUERiNlMrWmcwCnVZV2JVdlBiT09kbTBqbmZPVUg0
            VkoyV0wyMjZYb3VWYTc1czJsQzdNNTQKLS0tIDZkVit6VTVLZGR5cmtMZWxmU1Q2
            QW8vVTlSK2VzRXRKSWRiZ1JHTEVEdGsK/HHANM5kmmEn5wKXEmyQctIW9OT0A0hk
            TWf84C7EaQYElei5cr/kvHZXNWFakbHaksClSADjDH0tUBzvfvQXYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbmRia0VIZmIxc2tXVWdQ
            c21XWmczWFZKcHR6OUxkREtOVVlhV1VxY0FrCkRjWlUvNWdBaldkbEp6d29HNkNM
            NGg3NGVPQTRDREJ3S2QxTXRIWjVYSGcKLS0tIGwwVFhrZXcrSkVXa0xWQ2RIWlVt
            SWtMTXFvTEpFYkdBNXFLaVQ1cG9NNU0KtRiYqWEqcuFZaKq7pUwUljnU2pGUPfZk
            idW6UUjNr5OqifEhENOlQd+046NJQWfqDO9ftR6LqKw8SP+8Z5QT6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T08:41:06Z"
    mac: ENC[AES256_GCM,data:Xi7zXcVDvo3oTs79byMBK/7vhl0w3dCavelk0ShPZOYx7pist19qdRk9JrdeDLLTWqimu3AkVQyToQdONwRL2jh/IjqtR43DBLIuL3paj0U+Pw3pREo578JcUE3RoWoz3NjRLJKNRk7wwbgFG0cGpA/IiwCFlFFKPxUyUweQ9Zk=,iv:IWWK1pFDcyPN+HT79nEuEs9r+FEJmBTvLLvGOzt3byM=,tag:HvdCAzP3WtGuvezyrZOZbQ==,type:str]
    version: 3.13.3
