apiVersion: v1
kind: Secret
metadata:
    name: coder-secrets
    namespace: coder
type: Opaque
stringData:
    db-url: ENC[AES256_GCM,data:+GUra3I+HRvW/MPkFVCuKrpkFZhZ0Jc5mPgzGQc0fJe+Qboj8ULTksxMFrlhMLwETRAe4uW/6iY3yGhuAbUmqz5fwMVE/ZJPvzFQQ4GaKfIgc0/wYwDvhGSnddm4Rn2JAvTMUXXvT+FRIbdGc4j9h/Qj+5c=,iv:1wKfdJeo7wCtOlivzJV7YIgmnD7ZRLj1uERFVRLgttw=,tag:MIJEFwnA8YBaQNTQW5KxJA==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:QlaPpOefSUFyWMvjw9UlXUHyFzQ3R1mpUXi0yXxcoXJKOnsa,iv:S3kvtaWjaX+ZOL/YfAZ3VlmcX+JGcRcheMQdamanCsU=,tag:LppvC8NxDwqQIyZuHeCMWg==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:CQUws4/OoAGcpgqkHzP1alKNzDyo+63TlFDWgp0pIfD8TKvZ5YILrdhXidLMzIlUk9THwVx45Er9FGgG3O90zQ==,iv:lz0aaM701KwRbY9NOyqnMCxUzvM0bPkyPD+dNA1xtjo=,tag:Ybz7YDeddqwr2eIgc+JIYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMTlGckl5VWlrcFBpVzRD
            MTBtOG5mY1RBNmRCOWxHMnQ1a0VWUHVpVHo4CjVqeWUva3RjNldOOVFaelFUb2lu
            SnZpMmlBK3Z1Nk16eWVWWDVRSWZaOUUKLS0tIEVXQWVnTzd2R0h2NnArOXQrTTBG
            VWRZSGJCeGQ1elhQRmRPTWNZSUtFUkkK+VMDQI+YoaFWK5G8iqBcDNN3MFxt+xSg
            bGSuuEywma6Lr3iLchaS2cbAidMEaaCpfAs7W8ppwgWM68zMChKp0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRjBCZlFtM0l2UE4wNndO
            V2lodVZuSlAvUUlTNmJyK1BKSC9CR0trOEgwCmRMUmlPblVGUk1RN2JNeDR1TXVq
            TjdDY2FPQjRONngxZGVGMnVSc096RGsKLS0tIHRFS3lxRVBhcVVHTjZ4ZFVOK2Mv
            SkJxRjBFbWRHWTBmWjczcmZ2Ny9ybzgKcQi0CsKoEQjIQhmxihq877N1+RRHH88T
            TZIc0T+JS3HmZBwQ2g6astuPWmqZTuSBoxQrqMHhB6cIQ1Cv5o/zJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NEtkZkU5Y3grbGR2bWRC
            Qk1TRExYTmVEVndCdzVsM0hTeGVoQkdJOVM0CjF2M01SdUIrZExjUWdxTDdDUHor
            d1l0MWllZXAyY0Y5eEYxbVREb3FlYjAKLS0tIFJqN1hIYnRTTk1KdlMxRmx1bEN6
            RUpxR01CaG9rNm1uek9PZEVLRStIZmsKIMUPnSMdD+HHs2ejalLJPCDXKQuJC4uN
            Ho/q/w3letEZBjSFKqy2p3ZjgbEsE5r4QR5t9b395nftYMzs7L+FlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWUdPV3ZOSVJXem44U1VT
            ZkN3bVlic2VOWnRGeGI5VVRIdnIyb3RLdERrCmJvUCtJL3JyQTMrbjFiNytqWnIw
            TzJKL3d1L1VHK05jb2luZVBydi9mancKLS0tIGd1cm45alM0VnlmLzR4WDE0ZXUv
            a3c5aiswVEJGbzhnM08vMGo5S2x1eFEKZ9KSyso+UXpHZIR0TuCAkhJNYe9O5ES2
            K1Fvbq7nJCbT1k7oHFQaEY7DEKEFxlbwGONd0p8oQI9SUyTMxuyzSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T17:01:29Z"
    mac: ENC[AES256_GCM,data:kQunZU1CzY1i7jL6sAqO8VkkOxnuBv1v0RmFgCWcZ/ay3xGRPFjlqwTWeVTMbTp4T7ZnwT7x/+Q3qywOUzEJN8fPeT2xnexpTG5PIi+SsE4oNpEo2rSk1ZrggxyW6KeNhrApa3j9DeQtpuD8Eb0RW448IGGQfUsLzNwtUO3Xlcs=,iv:EZx+x8FI1aJ5o+yjeyovI7qwtBfkjrb5UzntsCMhze8=,tag:Nw/MKlx7tz78mCpO2/ZVcg==,type:str]
    version: 3.13.3
