apiVersion: v1
kind: Secret
metadata:
    name: ovh-domain-secrets
    namespace: cert-manager
type: Opaque
stringData:
    OVH_APPLICATION_KEY: ENC[AES256_GCM,data:bBdTOGEjh06Smjvd8kiuhA==,iv:q0q8WFa7BA5W+xwMB/vYsn28oRROsNCRqpUuM+ViqJA=,tag:0Lxyxx5wa+1fF4Bhvnkmpg==,type:str]
    OVH_APPLICATION_SECRET: ENC[AES256_GCM,data:vEqE+etr80J1Js65Yi6hwfz2ycllNKJlAjxOAWfmRa0=,iv:sIcNT9UM0GTISi1yFtT5vEJe5gR6N1b5lRmiczT1QPc=,tag:Y0YceB2upC/SYL9QMNPVSg==,type:str]
    OVH_CONSUMER_KEY: ENC[AES256_GCM,data:B3A7uJLUh+ufNgixP3xQJY7Ee7kk3HFQxUBDSFL2FN0=,iv:cQ/KG5i8bYc4i07Z2aHJ/hXbNMmrSv6efgXGvPImdfw=,tag:mHb7+0zhc5AYSoYqxGGJvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNHB5cnZudGRjV1NrODBz
            V0F2cWl6bFY2WFF2SXBObkkzV0VpU0xGRGx3CnlnaE9udE5xazFBUWF3MXJ5ZVB4
            dWtza0ZMeExJTldBSGtqd29HaDdzNjQKLS0tIC9xWXkvRzlHVEJpeVFXdTVhMTVq
            L3VrTDRFQzczYlVWZk1HdWpEb2FWSmsKzmsaDWR0hcdZMUMDNdRVQpb9uuYhzBnD
            ex6t3jsOvo9l0tBdg8wHpZPt9Q25sx7hEGgHnVcwSi5h/tWpKfwagw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3FPMFNtRDkweDM0Q04z
            YmhrTEJIOHpIbHphL2N4SXhGdTk3b2ppSm1BCmpDaWpoKzZOakozV1AxQm5UalNL
            UE94RGRZZFhOMGtBcGRZdEJmaG9RREEKLS0tIEN3bVZObkxFU3o2eDMwQXFQOExX
            KzJGQWdJY2p1TVl3SkVqQjg1VHlsZFEK/D/Pi2wEt5Us+4BVLt829a9sn1LKvymO
            BQ9Uhi4Vm34jVUMfFCSmoiYbilG43mcCwsofkH5yylYzZ8UkKaQhTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYThEaGlVdHIwNW8xbWZV
            ME1lNzNpZTZvMjlFZEJqOUZqQzAydEJXWnprCjlSaVBHT0hlRmVXVmV4QnRHcjZR
            Wi9jcjUwTmNCa2Nad0NtUFc0M3RIc00KLS0tIE9PTmpxanpyT3FoZm8zQVVSTzQr
            QUZvUGs3UG9hMFBnYzJFSjRpZzFVcE0KC6GsclK+LJXeL5wMYTJm+aMe/MvcY6Mb
            Aq6e4YhvHS1EqSasIpQPKYiMtZKK6e72UK+HFeugYO+G7SP3NA3rmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Tzh3cnpRKzV0VFJOM1pC
            WmVSRWw3TVBwamRkVlVDSktjb2tSRC85S0M4CjYrL21CbUlDWWcyNk9LYnVyWktx
            UXhUYitTZ1VpK2FxdW8rU0NnRWhoSFkKLS0tIENCNGRNQ09scG5za1d3eExtSGk2
            NHAvUW4yV2Vna0hyMEpKU2hwYWNWT0EK5vsPoB6JSZB4W5ZU038/kKRaXc29YI9Z
            rHjxc0jpyBdXk9o7epX4GjNeN4+BVmDo/cBnHEO0INW2vy1SV+Phdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T10:23:18Z"
    mac: ENC[AES256_GCM,data:ZtVDCvuC12GQ9VWS9Ya/zrArDgvLJsYs6iXZic2M+WFqLpmHx8NZapcpgoDntBQwiS/RBfE2PBE0D6z9K5rvevyOG6yJ1fezltVAPNDAEdcS3HYdp3rPpmVOh1OAWjyfiiAwuYt1A+fxUhDtBgvWlxTqZPcGVyiW4htOB2szyGw=,iv:h9DteSAmTZKJvudXllpw5zTX0XdiQ85elvsMD0fjeAo=,tag:31MtN0KVsR9YiVWypmQAIQ==,type:str]
    version: 3.13.3
