apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-secrets
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:CZf3a1KLySJgaBwSSMmVcFxJrFU=,iv:GP8UvVlvRZGklF1i5kwhTliGDQHwbp4rP7tETGEcA/s=,tag:HNahRlfAhVo7zHMUW9xt7Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hYnTRe4FVP/PBM+0HJXuDPbP2fONsf76mEB27jpcOyOhcuFuLAwg5A==,iv:O6YMAFYqPdp8OtmmXNUrIb0rew83UBvLMKYCWD4oOYM=,tag:2Aws4ZPPrvPT8FKe7+d/Jg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:vMi/SECThhw/,iv:4hQ925s6HWPQQG+40L105+t9p4d5vAaXhEi6OvgjGec=,tag:qOfqHliqmcVm26e+ydE0/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUytLZDF3a2dBK2Y5Q0Y4
            dWpuWktmNS9CT1FsS1czaVUvQmVEekQ5cjFBCmowdjZCUVpKNGx1dTU3bFp2Vk9y
            dWFvZGFINnZjajd2YjJMcnpXTUtOdWsKLS0tIFJDVDgwYTlwTS9nL1QrRlA5RGw0
            YkJMa2piM0Y0WXN4c0M0SittZXF5K0EKOoGRX5Z5sp9ITpNb8uiGdB2ZI4HKmYtZ
            iw92yLxVs++o9UJBjLYNTkItogvbiMGKR+aCWvDR+m8z33siVX3i+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSXh3YlVSTmF3YjBJKzlm
            WEtsdm91V3lDaCs0amsycUVBWkkyNWdwRER3CmU4NWs4SjhlbWxiMUl3YVl0RGpR
            Y0oxYzJCT3MrRTNrZzJKTkhRV2VVVkUKLS0tIEUzbkxuemdmNkNId0ZzV0VFeGNT
            aGZ2NDJvOTJ4WjJ1ekxlVjIzR0ZNTzAK1NO6OTvx+rJtn+DobLh/Qc9+ShCW2QL0
            xmPKN5uvvT0CC1mXkvKccRYjl1NeMesMJ5tKZjUaxCdz1wk1997kyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UlJVVi9sakpLQ0JFTnVI
            R2U0MXZMTHNmT1ZhRXloRXg0ei85ekRvQXpBCnVqUUxKQTlRQ3FqUmdVVURMTDh0
            dENCbkZleUs3ZWhMT25RR3FtbGpUTFUKLS0tIG05VVloWWdQZ2N5Nm9CT255VHNZ
            c0dLaVcrRVlsYm1kakFVQ2w5eG5ST1UKOqzcsybe32pqrGDD65QCVt8qfsdBE0Rq
            2+JUatUs9p9UwVryfW5nxja8peMfKeR2Vmmif46ZVzJswrc92Heijg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzM01Wd3NtOVI3dGxXZFVu
            c0pJbTZiT20zblVWT29YUUZONzJLcmg5cjJFCnVzV0pmODByTFQvZ3ZXS0ZDUGMy
            Uk9sbXorR1lZanF4VDR5UmpiejE1NVEKLS0tIE1zZ1FaaGNhTVJ2TzhNcFk1TGVp
            UjdxQTBNdzB1RUdUZVZJSEFQTDhiUEUKooMpcYNmuiR59F7TQxiUDkHd4Y4ZzRKv
            4Evf9Nm2tmk1oCRMXhyD7c2Vzv4hzAl+x9L5iVP6DcQ4nO/Btj19aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T18:59:06Z"
    mac: ENC[AES256_GCM,data:KHyEaR6pvCXtvmDGFgBMVTgH4E1BvHOzg/RtXDCGZK/kjkaj75OQfDyFabgr4SwoVQD5ag2/s2x08olGOYtqo4Zp7jKx5N17oFI8f1kIkhS1KoGfQMNJ99hYhCQXdDax5lUKm9aqqX2Ne3OOVnGxgElfH9DwACsvneotLlsb4VE=,iv:6aJQr+SpdEizKOeYq3aayOEJhaYqiaKE21W/DtPxy84=,tag:kL+QIp3mU5rWiVURoffAGg==,type:str]
    version: 3.13.3
