apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-secrets
    namespace: databases
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:hS136B5IhCTQiOq+9pvMBnOe5FU=,iv:2IQe0YyGflgL0Rhpq+bC0+tDa4fdn8oXJx75qHGCYNA=,tag:8MbqR+7kSJBsZnFef/qwPA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+fpTvA1LVdO+ZcD8cqxZl6FL0ee63trQQ35B+7pgkd3vk5E7nooe4Q==,iv:DnzQoNIqND7rGqToont9s9FZBJbVTg5A8VmJNzl4bp0=,tag:TohMtTb8C1YhpBBV/8EgLA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:h0HQLMCdmbQC,iv:Ea/JoS3vygruJcpiLWU44RUXP6hLlSm25seJet8e5zo=,tag:QT/cLkizR5wBCSNYlLephg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoblhjNk9UR29rT2hNTlYr
            NldaS0FWUTBZTXZIbDFXWHM3cGZyUHlyZVR3CkwyUkVJMDBRemNMN1l3dytsTGxR
            S1FvQ1dOQmJud3MvRkhDY2lBdWViWlUKLS0tIEx2SXpJWTZINW1YSWpKN0Y1Vk9G
            bnNaTG1qV1NOZXZWUXlqZnVWSmQyMmsK2vTif1cZFiElufY0AChWoSYUsHNvke0O
            x2vuPnJyjCtmP+WhzUl4qFF+irRBn65wsdhFPxrO+m9MMYt6Bm+yOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t5z4ef69wlwewylplzr5pphrgwn5weqetkrmyuel9p8qr9p7j39q5ux7ak
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcElsaHBGRzdGNjVSVzRJ
            ZTM4UXA3eW12MFhzTHNDM2NrYmJCbHJTV0hrCjh5dmpJeEdSN3Vtd3ArOW9qMC90
            ZW43Vnk2TFVQcmJTTDNjeE5CemIvQU0KLS0tIGZCdW1HWTJvdG1lNHhwV0pSSG9a
            WTZCeCtOZVpseU9sMXlZeXZFL3NuanMKwpXr0cKXMTB/C25NQke473PydjHsEqLB
            LEoorVek6tq0MIhCeFebZPghlJEdfSAd2WlmvmpwMuAGBUjrqIkGZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5w6y8mh0cq00w8k3du5fk3ct92pyr5z3kdy9ww5w7avgwycgdtq2ezmt3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVUhJeDFlVjlneGh6NWQw
            dVEvamU3TGNvSm4yZmhqTHFJZGI0bmZyZEY0CnFjUCt4ZUlOL1YvZHNIVWlGTVBu
            WVV2dHNreUVQWDRhTlpKeTJYbDU2WGsKLS0tIFNPcm5WQnZoUlNVN2RpZUR5MnNy
            b3lkSzlHNmM1R3VwdHVPVTJDTXFmSDgKdLiwkDtYU/7cCtmb18tUsy3DaOjAi/RT
            k5MyJoaVqT3VAI8ltFNZsJt/Gd7xoNMIG/7Dh2RySo68Gz6E3Cuv6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wynx7pnkg8z6n20zxg2krecmgyy5gdlj6xrs2tmfjctefy2xwv3qa2v24g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSzJmNjRndTFTTjdMbTVX
            ZjMxU0d4ZXNidmFSbmE4Nm13MVlHWGxuaDFZCnZZTVhiU0tORDZiZ1V5eFlVdmIr
            Y0I5dDJQTnp4QmtWWlRuMFdYa3hSWlUKLS0tIEtNb3BWc2xWT25uY25UVHc3enVa
            K1V0dVh4RFp5NWFYd21vUDFnckJ6YlkKzhSTJGYGQMlTrkr/26ZMrBe5eRh8a7MF
            gT/qfxFFWHoa86CorrsP0AuLSkB6NdKFy0nvw0qVy6WMaL4Gtk6MsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewq0v3rjm0y4m86xq9z555weuspsklz4sz07emhx4awqttjd9sjqnf2t3u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T21:13:15Z"
    mac: ENC[AES256_GCM,data:hZW4Z8Bf4sJnYE9wG7eC+JfMEzQs2Nx9RPPUdDSQWNdsxB1Q1lrtB68GHScN7HlVVkt0xHlvKpZJDemIqfTZPO68Y3+VKfFBO1YMm+ZZpl1nBp5QGRusAZ9tkz5bcTx21T+EnnfA1EaYTO8dXN+aFXRjbdLhIA1fwFXn85Z3kO4=,iv:XeLKmcL44CQhI8D4MuS/R8Jr0CcXEfdzKezscpAUVA0=,tag:rTl4tY22vfdVF5f4LkxkKw==,type:str]
    version: 3.13.3
