apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/cert-manager.yaml
  - cert-manager/ovh-webhook.yaml
  - k8s-reader/namespace.yaml
  - k8s-reader/serviceaccount.yaml
  - k8s-reader/clusterrole.yaml
  - k8s-reader/clusterrolebinding.yaml
  - k8s-reader/serviceaccount-token.yaml
  - reflector/reflector.yaml
  - cnpg/operator.yaml
  - storage-retain.yaml
